#:schema node_modules/wrangler/config-schema.json
name = "hlwfq-dyzh"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "28176cc0f3e34d5cad76fcada51e13a9" }
]
